### ISSUE TITLE
Cannot render Facebook tabbar

### ISSUE THREAD

**Issue by isikfsc** [brentvatne/react-native-scrollable-tab-view#84]
I am trying this library's components on ReactNative Playground.

I could not have rendered `<FacebookTabBar />` (neither as topbar nor as bottom bar). The tab view in the example of the repo is rendered, and possible the other tabviews, however, I cannot swipe or in any other way swipe to them.

**What can be the missing point here? Is there a bug, or is it not supported for current RN version?**

This is the link to repo's example on [RN Playground: https://rnplay.org/apps/PfJrnA](https://rnplay.org/apps/PfJrnA)

Thanks for the repo, it is what I would like to build to use in my current project. After a lot search I was thinking this will not be possible, but I have seen this repo. Something like this should be even built-in RN.
For the rugby example I do not know how the working version looks. A link to this [other example of yours](https://rnplay.org/apps/D5ioJA). It seems problematic.

**Comment by isikfsc** [comment]
Ok, ı think I have made a mistake copying and pasting the code in replay.
Since it does support one file for platform, I needed to merge the code of files of library, and code of files of example.
While doing so I had many `style`vars in one file. I have corrected that now.
But the icons are missing but this can be due to replay does not support them. I will look for solution later.

mpphh. this repo seems left. Is it really? Since this is nice work, it should go on.

**Comment by brentvatne** [comment]
Hi @isikfsc! I just updated this today and published 0.3.0, I would suggest using this version. The FacebookTabBar example works now! I haven't had time recently to work on this until today, let me know if this solves your problems.

**Comment by brentvatne** [comment]
Closing due to inactivity and because I'm confident that 0.3.0 fixes this :)

**Comment by robtg4** [comment]
This still isn't working. The following error comes up when in use: 

![screen shot 2016-01-04 at 3 14 56 pm](https://cloud.githubusercontent.com/assets/13613075/12099382/19c3b2f8-b2f6-11e5-8d09-991f45c84b8e.png)
